#!/bin/sh

set -e -o pipefail

if x11appjail sys-attr check network.mode; then
    NETWORK_MODE=`x11appjail sys-attr cat network.mode`
fi

NETWORK_MODE="${NETWORK_MODE:-none}"

set --
set -- "$@" -j "${X11APPJAIL_JAIL}"
set -- "$@" -f "${X11APPJAIL_WORKDIR}/Makejail"

if [ "${NETWORK_MODE}" = "inherit" ]; then
    set -- "$@" -o alias -o ip4_inherit -o ip6_inherit
elif [ "${NETWORK_MODE}" = "virtualnet" ]; then
    if [ "${APPJAIL_SELF_CONTAINED}" != 0 ]; then
        echo "ERROR: Virtual Networks requires AppJail to be installed on the host."
        exit 1
    fi

    if x11appjail sys-attr check network.virtualnet; then
        VIRTUALNET=`x11appjail sys-attr cat network.virtualnet`
    fi

    set -- "$@" -o virtualnet="${VIRTUALNET}:<random> default" -o nat
else
    if [ "${NETWORK_MODE}" != "none" ]; then
        echo "WARNING: invalid network mode '${NETWORK_MODE}', falling back to 'none'" >&2
    fi
    set -- "$@" -o alias -o ip4_disable -o ip6_disable
fi

if [ "${NETWORK_MODE}" = "virtualnet" ]; then
    SECGRP_TABLES=

    if x11appjail sys-attr check network.security-group.tables; then
        SECGRP_TABLES=`x11appjail sys-attr cat network.security-group.tables`
    fi

    if [ -n "${SECGRP_TABLES}" ]; then
        set -- "$@" -o label="security-group:1"

        for SECGRP_TABLE in ${SECGRP_TABLES}; do
            set -- "$@" -o label="security-group.tables.${SECGRP_TABLE}:${SECGRP_TABLE}"
        done
    fi
fi

set -- "$@" -o mount_devfs
set -- "$@" -o device='include $devfsrules_hide_all'
set -- "$@" -o device='include $devfsrules_unhide_basic'
set -- "$@" -o device='include $devfsrules_unhide_login'

. "${X11APPJAIL_WORKDIR}/perms.sh"

if ${ENABLE_3D_ALREADY}; then
    set -- "$@" -o device="path 'dri' unhide"
    set -- "$@" -o device="path 'dri/*' unhide"
    set -- "$@" -o device="path 'drm' unhide"
    set -- "$@" -o device="path 'drm/*' unhide"
    set -- "$@" -o device="path 'pci' unhide"
    set -- "$@" -o device="path 'nvidia*' unhide"
fi
if ${WEBCAM_ALREADY}; then
    set -- "$@" -o device="path 'cuse*' unhide"
    set -- "$@" -o device="path 'video*' unhide"
fi
if ${USB_ALREADY}; then
    set -- "$@" -o device="path usb unhide"
    set -- "$@" -o device="path 'usb/*' unhide"
fi
if ${SOUND_ALREADY}; then
    set -- "$@" -o device="path sndstat unhide"
    set -- "$@" -o device="path mixer unhide"
    set -- "$@" -o device="path 'mixer*' unhide"
    set -- "$@" -o device="path dsp unhide"
    set -- "$@" -o device="path 'dsp*' unhide"
    set -- "$@" -o device="path speaker unhide"
    set -- "$@" -o device="path 'speaker*' unhide"
fi

if [ -n "${X11APPJAIL_EPHEMERAL}" ] || \
        x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.jail.ephemeral" "${X11APPJAIL_UID}"; then
    set -- "$@" -o ephemeral
fi

if x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.labels"; then
    LABELS=`x11appjail sys-attr cat "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.labels"`

    for LABEL in ${LABELS}; do
        if ! x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.labels.${LABEL}"; then
            continue
        fi

        VALUE=`x11appjail sys-attr cat "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.labels.${LABEL}"`

        set -- "$@" -o label="${LABEL}:${VALUE}"
    done
fi

if x11appjail sys-attr check mount.system-fonts; then
    PREFIX=`x11appjail prefix`
    FONTSDIR="${PREFIX}/share/fonts"

    if [ -d "${FONTSDIR}" ]; then
        set -- "$@" -o fstab="\"${FONTSDIR}\" /system-fonts nullfs ro"
    fi
fi

mkdir -p -m 0755 -- "${X11APPJAIL_USERDIR}"
set -- "$@" -o fstab="${X11APPJAIL_USERDIR} data <volumefs>"

set -- "$@" --
set -- "$@" --puid "${X11APPJAIL_UID}"
set -- "$@" --pgid "${X11APPJAIL_GID}"

OCI_FROM=
if x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.oci.from"; then
    OCI_FROM=`x11appjail sys-attr cat "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.oci.from"`
elif x11appjail sys-attr check "oci.from"; then
    OCI_FROM=`x11appjail sys-attr cat oci.from`
fi
if [ -n "${OCI_FROM}" ]; then
    set -- "$@" --from "${OCI_FROM}"
fi

OCI_TAG=
if x11appjail sys-attr check "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.oci.tag"; then
    OCI_TAG=`x11appjail sys-attr cat "${X11APPJAIL_APPNAME}:${X11APPJAIL_PROFILE}.oci.tag"`
elif x11appjail sys-attr check "oci.tag"; then
    OCI_TAG=`x11appjail sys-attr cat oci.tag`
fi
if [ -n "${OCI_TAG}" ]; then
    set -- "$@" --tag "${OCI_TAG}"
fi

exec "${APPJAIL}" makejail "$@"
